[package]
name = "fuju-trace-engine"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
fuju-trace-core = { path = "../fuju-trace-core" }
fuju-trace-manifest = { path = "../fuju-trace-manifest" }
fuju-trace-wal = { path = "../fuju-trace-wal" }
fuju-trace-memtable = { path = "../fuju-trace-memtable" }

[features]
test-failpoints = []
